# Change these first
owner: serenysoft
repo: status

sites:
  - name: SerenyCRM - Server
    url: https://serenycrm.com
  - name: SerenyCRM - App
    url: https://app.serenycrm.com

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/serenysoft/status/refs/heads/master/assets/sereny-icon.png
  name: Sereny - Status
  introTitle: "Sereny - Status e monitoramento dos serviços"
  introMessage: "Monitoramento do status dos serviços da Sereny"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
