# Change these first
owner: serenysoft
repo: status

sites:
  - name: SerenyCRM - Server
    url: https://serenycrm.com
  - name: SerenyCRM - App
    url: https://app.serenycrm.com

status-website:
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/serenysoft/status/refs/heads/master/assets/sereny-icon.png
  name: Sereny - Status
  introTitle: "Sereny - Status e monitoramento dos serviços"
  introMessage: "Monitoramento do status dos serviços da Sereny"
  theme: ocean
i18n:
  activeIncidents: Incidentes ativos
  allSystemsOperational: Todos os sistemas operacionais
  incidentReport: "Incidente #$NUMBER relatório →"
  activeIncidentSummary: Aberto em $DATE com $POSTS postagens
  incidentTitle: Detalhes do Incidente $NUMBER
  incidentDetails: Detalhes do Incidente
  incidentFixed: Corrigido
  incidentOngoing: Em andamento
  incidentOpenedAt: Aberto em
  incidentClosedAt: Fechado em
  incidentViewOnGitHub: Visualizar e Inscrever-se no GitHub
  incidentCommentSummary: Postado em $DATE por $AUTHOR
  incidentBack: ← Voltar para todos os incidentes
  pastIncidents: Incidentes Anteriores
  pastIncidentsResolved: Resolvido em $MINUTES minutos com $POSTS postagens
  liveStatus: Status ao Vivo
  overallUptime: "Tempo de atividade geral: $UPTIME"
  overallUptimeTitle: Tempo de atividade geral
  averageResponseTime: "Tempo médio de resposta: $TIMEms"
  averageResponseTimeTitle: Resposta média
  sevelDayResponseTime: Tempo de resposta de 7 dias
  responseTimeMs: Tempo de resposta (ms)
  up: Online
  down: Offline
  degraded: Degradado
  ms: ms
  loading: Carregando
  navGitHub: GitHub
  footer: Esta página é [código aberto]($REPO), powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Limite de requisições excedido
  rateLimitExceededIntro: Você excedeu o número de requisições que pode fazer em uma hora, então terá que aguardar antes de acessar este site novamente. Alternativamente, você pode adicionar um Token de Acesso Pessoal do GitHub para continuar usando este site.
  rateLimitExceededWhatDoesErrorMean: O que significa este erro?
  rateLimitExceededErrorMeaning: Este site usa a API do GitHub para acessar dados em tempo real sobre o status dos nossos sites. Por padrão, o GitHub permite 60 requisições por hora para cada endereço IP, que você já consumiu.
  rateLimitExceededErrorHowCanFix: Como posso corrigir isso?
  rateLimitExceededErrorFix: Você pode aguardar mais uma hora e o limite do seu endereço IP será restaurado. Alternativamente, você pode adicionar seu Token de Acesso Pessoal do GitHub, que lhe dá 5.000 requisições adicionais por hora.
  rateLimitExceededGeneratePAT: Aprenda como gerar um Token de Acesso Pessoal
  rateLimitExceededHasSet: Você tem um token de acesso pessoal configurado.
  rateLimitExceededRemoveToken: Remover token
  rateLimitExceededGitHubPAT: Token de Acesso Pessoal do GitHub
  rateLimitExceededCopyPastePAT: Copie e cole seu token
  rateLimitExceededSaveToken: Salvar token
  errorTitle: Ocorreu um erro
  errorIntro: Ocorreu um erro ao tentar obter os detalhes de status mais recentes.
  errorText: Você pode tentar novamente em alguns momentos.
  errorHome: Ir para a página inicial
  pastScheduledMaintenance: Manutenções Programadas Anteriores
  scheduledMaintenance: Manutenção Programada
  scheduledMaintenanceSummaryStarted: Iniciada em $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Inicia em $DATE por $DURATION minutos
  startedAt: Iniciada em
  startsAt: Inicia em
  duration: Duração
  durationMin: $DURATION minutos
  incidentCompleted: Concluído
  incidentScheduled: Agendado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1a
  durationAll: tudo
  locale: pt-BR

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
